USER=abc324
DOMAIN=cse.lehigh.edu

# TCP_PORT=1895
# TCP_PORT=5000
# TCP_PORT=4040
# TCP_PORT=4041
TCP_PORT=6000
# TCP_PORT=6010

# MACHINES+=("ariel") 
# MACHINES+=("caliban")
# MACHINES+=("callisto")
# MACHINES+=("ceres")
# MACHINES+=("chiron")
# MACHINES+=("cupid")
MACHINES+=("eris")
# MACHINES+=("europa")
# MACHINES+=("hydra")
# MACHINES+=("iapetus")
# MACHINES+=("io")
# MACHINES+=("mars")
MACHINES+=("mercury")
# MACHINES+=("neptune")
# MACHINES+=("nereid")
MACHINES+=("nix")
# MACHINES+=("orcus")
MACHINES+=("phobos")
# MACHINES+=("puck")
MACHINES+=("saturn")
# MACHINES+=("triton")
# MACHINES+=("varda")
# MACHINES+=("vesta")
# MACHINES+=("xena")

# MACHINES+=("ixion")  // no longer available? 
